// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo5dJT5FWR01KJhlsVdoTQI9cm7Kh8Zlo',
    appId: '1:52989495746:web:2abc1299df77bd12906e5b',
    messagingSenderId: '52989495746',
    projectId: 'snack-over-vbt',
    authDomain: 'snack-over-vbt.firebaseapp.com',
    storageBucket: 'snack-over-vbt.appspot.com',
    measurementId: 'G-Y6VKKV50E0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSiMAQbeTEALEzno-Rp9SDvMnZgKtYzTs',
    appId: '1:52989495746:android:65d1ad06b826b2a3906e5b',
    messagingSenderId: '52989495746',
    projectId: 'snack-over-vbt',
    storageBucket: 'snack-over-vbt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr2xZd9TgNY5m7Qvn7wu2yXkYyj0O_180',
    appId: '1:52989495746:ios:64b43e7424b2f4e8906e5b',
    messagingSenderId: '52989495746',
    projectId: 'snack-over-vbt',
    storageBucket: 'snack-over-vbt.appspot.com',
    iosClientId: '52989495746-qtkifet32r6lnhs4ooqqtvob7bir8gcl.apps.googleusercontent.com',
    iosBundleId: 'com.snackovervbt',
  );
}
